apiVersion: v1
kind: Service
metadata:
  name: {{ include "AdGuardDNS.fullname" . }}
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "AdGuardDNS.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIp: {{ .Values.service.ip }}
  {{- with .Values.service }}
  ports:
    {{- toYaml .ports | nindent 2 }}
  {{- end}}
    
  selector:
    {{- include "AdGuardDNS.selectorLabels" . | nindent 4 }}
