# === Presistant Volume 'adguard-pv-work' ===

apiVersion: v1
kind: PersistentVolume # Is our initial 'bucket' we use to store data
metadata:
  name: adguard-pv-work
  namespace: adguard
spec:
  capacity: # Sets maximum capacity what can be reqested from this volume
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Allows acces only from single node
  nfs:
    server: 192.168.6.3
    path: /mnt/Main/k8s/AdGuardHome/work
    readOnly: false
  mountOptions:
    - nfsvers=4.2

--- # === Presistant Volume Claim 'adguard-pv-work' ===

apiVersion: v1
kind: PersistentVolumeClaim # Out pod claim to use. Eats up from PresistentVolume
metadata:
  name: adguard-pvc-work
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce # Allows acces only from single node
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: adguard-pv-work